pyinstaller.exe .\horizon_golden_image_deployment_tool.py --noconsole ^
  --hiddenimport=requests ^
  --hiddenimport=horizon_functions ^
  --hiddenimport=horizon_app ^
  --hiddenimport=PySide6.QtWidgets ^
  --hiddenimport=PySide6.QtCore ^
  --hiddenimport=PySide6.QtGui ^
  --hiddenimport=loguru ^
  --collect-all PySide6 ^
  --name "Horizon Golden Image Deployment Tool" ^
  --noconfirm --icon=logo.ico --clean ^
  --add-data "logo.ico;." --onefile